# Generated by Django 5.2 on 2025-04-16 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='condition',
            field=models.CharField(choices=[('new', 'новый'), ('used', 'б/у')], max_length=10),
        ),
    ]
