# Generated by Django 5.1.6 on 2025-04-17 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0002_alter_ad_condition'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ad',
            name='image_url',
        ),
        migrations.AddField(
            model_name='ad',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='ads_images/'),
        ),
    ]
